<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StudentInfo.aspx.cs" Inherits="SchoolThreeTireDemo.StudentInfo" %>

<!DOCTYPE html>  
<html xmlns="http://www.w3.org/1999/xhtml">  
<head runat="server">  
<title></title>   
<link href="Content/bootstrap.min.css" rel="stylesheet" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"  
type="text/javascript"></script>  
<!--include jQuery Validation Plugin-->  
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate.min.js"  
type="text/javascript"></script>  
<style type="text/css">  
label.error {  
color: red;  
display: block;  
}  
</style>  
<script type="text/javascript">  
$(document).ready(function () {  
$("#form1").validate({  
rules: {  
<%=TextBox1.UniqueID %>:{  
required:true,  
minlength:5  
},  
<%=TextBox2.UniqueID %>:{  
required:true,  
minlength:5  
} 

},  
messages: {  
<%=TextBox1.UniqueID %>:{  
required: "First Name is required.",  
minlength:"FirstName should be minimum 5 characters only!!"  
},  
<%=TextBox2.UniqueID %>:{  
required: "Last Name is required.",  
minlength:"LastName should be minimum 5 characters only!!"  
}  
 
}  
});  
});  
</script>  
</head>  
<body>  
<form id="form1" runat="server" style="margin-top: 25px">  
<div class="container">  
<div class="row">  
<div class="col-lg-4">  
<div class="panel panel-success">  
<div class="panel-heading">Student Registration Form </div>  
<div class="panel-body">  
<label>&nbsp;First Name</label>  
<asp:TextBox ID="TextBox1" runat="server" CssClass="form-control" placeholder="First Name"></asp:TextBox>  
<label>&nbsp;Last Name</label>  
<asp:TextBox ID="TextBox2" runat="server" CssClass="form-control" placeholder="Last Name"></asp:TextBox>  
<label>&nbsp;Age</label>  
<asp:TextBox ID="TextBox3" runat="server" CssClass="form-control" placeholder="Age"> </asp:TextBox>  
<label>&nbsp;Gender</label>  
<asp:TextBox ID="TextBox4" runat="server" CssClass="form-control" placeholder="Gender"></asp:TextBox>  
<br />  
<asp:Button ID="Button1" runat="server" CssClass="btn btn-block btn-success" Text="Submit" OnClick="Button1_Click" />  
</div>  
</div>  
</div>  
       

<%-- Grid View Result --%>

<div class="col-lg-8"> 

    <div class="col-lg-6"> 
        <h2 style="color: darkblue">List of the student </h2>
    </div>
    <div class="col-lg-6">
        <asp:Button ID="Button2" runat="server" Height="40px" Width="180px" CssClass="btn btn-block btn-success" OnClick="Button2_Click" Text="Generate RDLC report " /> 
    </div>
<asp:GridView ID="GridView1" CssClass=" table table-bordered " runat="server" AutoGenerateColumns="False" 
     AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataKeyNames="Id" 
     OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" 
     OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" 
     OnSelectedIndexChanged="GridView1_SelectedIndexChanged">  
<Columns>  
<asp:TemplateField HeaderText="First Name">  
<EditItemTemplate>  
<asp:TextBox ID="Fnametxt" runat="server" Text='<%#Bind("FName") %>'></asp:TextBox>  
</EditItemTemplate>  
<ItemTemplate>  
<asp:Label ID="Label1" runat="server" Text='<%#Bind("FName") %>'></asp:Label>  
</ItemTemplate>  
</asp:TemplateField>  
<asp:TemplateField HeaderText="Last Name">  
<EditItemTemplate>  
<asp:TextBox ID="Lnametxt" runat="server" Text='<%#Bind("LName") %>'></asp:TextBox></EditItemTemplate>  
<ItemTemplate>  
<asp:Label ID="Label2" runat="server" Text='<%#Bind("LName") %>'></asp:Label></ItemTemplate>  
</asp:TemplateField>  
<asp:TemplateField HeaderText="Age">  
<EditItemTemplate>  
<asp:TextBox ID="Agetxt" runat="server" Text='<%#Bind("Age") %>'></asp:TextBox></EditItemTemplate>  
<ItemTemplate>  
<asp:Label ID="Label3" runat="server" Text='<%#Bind("Age") %>'></asp:Label></ItemTemplate>  
</asp:TemplateField>  
<asp:TemplateField HeaderText="Sex">  
<EditItemTemplate>  
<asp:TextBox ID="Sextxt" runat="server" Text='<%#Bind("Sex") %>'></asp:TextBox></EditItemTemplate>  
<ItemTemplate>  
<asp:Label ID="Label4" runat="server" Text='<%#Bind("Sex") %>'></asp:Label></ItemTemplate>  
</asp:TemplateField>  
</Columns>  
</asp:GridView> 

</div>  
</div>  
</div> 
   
    
</form>  
</body>  
</html>  
